  services:
    postgres:
      image: postgres:10.5
      ports:
        - "5432:5432"
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=elephant

      # volumes: 
      #   - ./subscriptions-rs/scripts/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
